services:
  db:
    image: postgres:17-alpine
    restart: always
    volumes:
      - cms_db:/var/lib/postgresql/data/
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_DB=cms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0KWqLNqxzG9VcLIkuN
    healthcheck:
      test: "pg_isready -U postgres -d cms"
      interval: 5s
      timeout: 10s
      retries: 5

  cms:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
      - ./.env:/app/.env
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

volumes:
  cms_db:
