# Generated by Django 5.2.2 on 2025-06-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_navbarlink_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarlink',
            name='sort_order',
        ),
    ]
