# Generated by Django 5.2.3 on 2025-06-15 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogindexpage_options_alter_blogpage_options_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Blog home page',
                'verbose_name_plural': 'Blog home pages',
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogListPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Blog posts list page',
                'verbose_name_plural': 'Blog posts list pages',
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameModel(
            old_name='BlogTagIndexPage',
            new_name='BlogListByTagPage',
        ),
        migrations.AlterModelOptions(
            name='bloglistbytagpage',
            options={'verbose_name': 'Blog posts list by tag tag page', 'verbose_name_plural': 'Blog posts list by tag pages'},
        ),
        migrations.DeleteModel(
            name='BlogIndexPage',
        ),
    ]
