# Generated by Django 6.0.2 on 2026-02-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blogpost_blogpostpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
