# Generated by Django 6.0.2 on 2026-02-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogcategorieslistpage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
