# Generated by Django 6.0.2 on 2026-02-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_category_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tag',
        ),
    ]
