# Generated by Django 6.0.2 on 2026-02-22 00:49

import wagtail_color_panel.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_category_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=wagtail_color_panel.fields.ColorField(default='#222222', max_length=7),
        ),
    ]
