# Generated by Django 5.2.2 on 2025-06-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_navbarlink_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarlink',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
