# Generated by Django 5.2.3 on 2025-06-29 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioLinkAccount',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.image', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Account to bio links',
                'verbose_name_plural': 'Accounts to bio links',
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BioLinkPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('multiple', models.BooleanField(default=False, verbose_name='show multiple icon?')),
                ('link', models.URLField(verbose_name='Link da postagem')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.image', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Post to bio link',
                'verbose_name_plural': 'Posts to bio links',
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
