name: Publish Container to Registry

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    name: Publish to Registry
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Login to Magalu Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://container-registry.br-se1.magalu.cloud
          username: ${{ secrets.MAGALU_CR_USER }}
          password: ${{ secrets.MAGALU_CR_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: container-registry.br-se1.magalu.cloud/cms/cms:main,container-registry.br-se1.magalu.cloud/cms/cms:${{ github.ref_name }}
